### ISSUE TITLE
Explanation

### ISSUE THREAD

**Issue by profesionalleet1337** [RozhakDev/Facemash#4]
Hey, I can't understand how exactly this instrument work, and does it work nowdays ( 31.12.24 ) ? - Does it have any video or tutorial, to understand and see how this should be used ? Thanks !

**Comment by RozhakXD** [comment]
This is just a tool to brute force Facebook and it only applies the technique of guessing passwords from the list we have. It still works now but not on all good providers!

[Google Drive](https://drive.google.com/file/d/1IbP1CHRwOzUKHyq0AZz9MbuzjQKhGdtL/view?usp=drive_link)

**Comment by profesionalleet1337** [comment]
@RozhakXD Thank u for the fast reply, could I contact ? Telegram, discord ?
